version: "3.5"

services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5555:5555"
    environment:
      - FLASK_APP=routes.py
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
